name: Automate Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changes
        run: files=$(git --name-only diff ${{ github.event.before }} ${{ github.event.after }})

      - name: Build docker images
        run: ${{ github.workspace }}/program/build_dockers.py --files $files