name: Run Program on Merge


on:

  push:

    branches: [main]  

  pull_request:

    branches: [main] 

    types: [merged] 



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - run: | 
          # Install mdxcanvas
            pip install mdxcanvas
          
          # Get version from stuff.md
            cat ${{ github.workspace }}/program/scratch/stuff.md
            VERSION=$(grep -o "version = \".*\"" ${{ github.workspace }}/program/scratch/stuff.md | cut -d'"' -f2)
          
          # Get version from mdxcanvas
            MDXCANVAS_VERSION=$(pip show mdxcanvas | grep "^Version:" | awk '{print $2}')
          
          # Check if versions are the same
            if [ "$VERSION" = "$MDXCANVAS_VERSION" ]; Please update .tomal"; fi
          
      
