name: Update Canvas Material and Notify Discord

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Store Current MDXCanvas Output
        run: cp ${{ github.workspace }}/.github/logs/mdxcanvas_output.json ${{ github.workspace }}/.github/logs/mdxcanvas_output_old.json || echo "No old output to copy"

      - name: Install MDXCanvas
        run: pip install mdxcanvas

      - name: Run MDXCanvas
        id: run_mdxcanvas
        run: |
          export CANVAS_API_TOKEN=${{ secrets.DEPLOY_KEY }}
          mdxcanvas --course-info ${{ github.workspace }}/scratch/testing_course_info.json \
                                  ${{ github.workspace }}/scratch/sample-content.canvas.md.xml \
                    --output-file ${{ github.workspace }}/.github/logs/mdxcanvas_output.json

      - name: Check if MDXCanvas Output Has Changed
        run: |
          if cmp -s ${{ github.workspace }}/.github/logs/mdxcanvas_output.json ${{ github.workspace }}/.github/logs/mdxcanvas_output_old.json; then
            echo "MDXCANVAS_OUTPUT_CHANGED=false" >> $GITHUB_ENV
          else
            echo "MDXCANVAS_OUTPUT_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Get User Avatar URL
        run: |
          AVATAR_URL=$(curl -s https://api.github.com/users/${{ github.actor }} | jq -r '.avatar_url')
          echo "AVATAR_URL=$AVATAR_URL" >> $GITHUB_ENV

      - name: Send notification to Discord
        run: |
          export DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}
          python ${{ github.workspace }}/.github/scripts/discord_notifications/send_notification.py \
            --type "canvas" \
            --notification-info ${{ github.workspace }}/.github/scripts/discord_notifications/notification_info.md \
            --payload "${{ github.workspace }}/.github/logs/mdxcanvas_output.json" \
            --author "${{ github.actor }}" \
            --author-icon "$AVATAR_URL" \
            --branch "${{ github.ref }}"

      - name: Commit Updated Output
        if: env.MDXCANVAS_OUTPUT_CHANGED == 'true'
        run: |
          git config --global user.name "robbykap"
          git config --global user.email "robbykap@users.noreply.github.com"
          git config pull.rebase false  # Ensure merge strategy
          git add -u 
          git rm --cached -r  ${{ github.workspace }}/.github/scripts/discord_notifications/__pycache__
          git commit -m "Update MDXCanvas Output" || echo "No changes to commit"
          git pull --no-edit
          git push