name: Notify Discord of MDXCanvas Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and Run MDXCanvas
        run: |
          echo "Installing MDXCanvas"
          pip install mdxcanvas
          
          echo "Setting environment variables"
          export CANVAS_API_TOKEN=${{ secrets.DEPLOY_KEY }}

          echo "Running MDXCanvas and logging output"
          mdxcanvas --course-info ${{ github.workspace }}/scratch/testing_course_info.json \
                    ${{ github.workspace }}/scratch/sample-content.canvas.md.xml | tee mdxcanvas.log

      - name: Extract Deployed Items
        run: |
          # Extract assignments and quizzes from the log file
          DEPLOYED_ASSIGNMENTS=$(grep "Deploying assignment" mdxcanvas.log | awk -F 'Deploying ' '{print $2}' | paste -sd ', ' -)
          DEPLOYED_QUIZZES=$(grep "Deploying quiz" mdxcanvas.log | awk -F 'Deploying ' '{print $2}' | paste -sd ', ' -)

          # Handle empty cases
          DEPLOYED_ASSIGNMENTS=${DEPLOYED_ASSIGNMENTS:-"None"}
          DEPLOYED_QUIZZES=${DEPLOYED_QUIZZES:-"None"}

          # Save to GitHub Environment Variables
          echo "DEPLOYED=$DEPLOYED_ASSIGNMENTS" >> $GITHUB_ENV
          echo "QUIZ=$DEPLOYED_QUIZZES" >> $GITHUB_ENV

      - name: Send Deployment Info to Discord
        run: |
          # Create JSON payload for Discord
          DISCORD_PAYLOAD=$(jq -n \
            --arg author "${{ github.event.pusher.name }}" \
            --arg branch "${{ github.ref }}" \
            --arg commit "${{ github.event.head_commit.message }}" \
            --arg deployed "${{ env.DEPLOYED }}" \
            --arg quizzes "${{ env.QUIZ }}" \
            '{
              "username": "GitHub Actions",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "Canvas Updates",
                "description": "`\($commit)`",
                "color": 16711680,
                "fields": [
                  {"name": "Author", "value": "\($author)", "inline": true},
                  {"name": "Branch", "value": "\($branch)", "inline": true},
                  {"name": "Deployed Assignment(s)", "value": "\($deployed)"},
                  {"name": "Updated Quiz(s)", "value": "\($quizzes)"}
                ]
              }]
            }')

          # Send payload to Discord webhook
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$DISCORD_PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
