name: Notify Discord of MDXCanvas Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MDXCanvas
        run: pip install mdxcanvas==0.3.18

      - name: Get User Avatar URL
        run: |
              USERNAME="${{ github.actor }}"  # Replace with the actual GitHub username or set it as an input
              AVATAR_URL=$(curl -s https://api.github.com/users/$USERNAME | jq -r '.avatar_url')
              echo "AVATAR_URL=$AVATAR_URL" >> $GITHUB_ENV

      - name: Run MDXCanvas
        id: run_mdxcanvas
        run: |
              export CANVAS_API_TOKEN=${{ secrets.DEPLOY_KEY }}
              mdxcanvas --course-info ${{ github.workspace }}/scratch/testing_course_info.json ${{ github.workspace }}/scratch/sample-content.canvas.md.xml --dryrun

      - name: Store Output
        run: echo "MDXCANVAS_RESULT=${{ steps.run_mdxcanvas.outputs.result }}" >> $GITHUB_ENV
        
      - name: Send notification to Discord
        run: |
              export TEST_CANVAS_DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK_URL }}
              python ${{ github.workspace }}/.github/scripts/send_discord_message.py --description "${{ github.event.head_commit.message }}" --message "$MDXCANVAS_RESULT" --author "$AVATAR_URL" --author-icon "${{ github.actor }}@avatar" --branch "${{ github.ref }}""
