name: Notify Discord of MDXCanvas Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MDXCanvas
        run: pip install mdxcanvas

      - name: Run MDXCanvas
        run: | 
              export CANVAS_API_TOKEN=${{ secrets.DEPLOY_KEY }}
              echo "TO_DEPLOY"=$(mdxcanvas --course-info ${{ github.workspace }}/scratch/testing_course_info.json ${{ github.workspace }}/scratch/sample-content.canvas.md.xml --dryrun) >> $GITHUB_ENV

      - name: Clean up TO_DEPLOY variable
        run: |
          # Clean the TO_DEPLOY value, remove "Items to deploy:" and add a newline after each item
          CLEANED_DEPLOY=$(echo "${{ env.TO_DEPLOY }}" | sed 's/Items to deploy://g' | sed 's/ - / - \n/g')
          
          # Escape newlines to preserve them in the environment variable
          CLEANED_DEPLOY_ESCAPED=$(echo "$CLEANED_DEPLOY" | sed ':a;N;$!ba;s/\n/\\n/g')
          
          # Set the cleaned and escaped value back to TO_DEPLOY
          echo "TO_DEPLOY=${CLEANED_DEPLOY_ESCAPED}" >> $GITHUB_ENV

      - name: Send commit info to Discord
        run: |
          # Convert escaped newlines back to actual newlines for the Discord message
          CLEANED_DEPLOY=$(echo "${{ env.TO_DEPLOY }}" | sed 's/\\n/\n/g')
          
          # Ensure the result is correctly formatted for Discord
          FINAL_DEPLOY=$(echo "$CLEANED_DEPLOY" | sed 's/ - / - /g')
          echo "FINAL_DEPLOY=${FINAL_DEPLOY}" >> $GITHUB_ENV
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub Actions",
                 "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                 "embeds": [{
                   "title": "Canvas Updates",
                   "description": "`${{ github.event.head_commit.message }}`",
                   "color": 16711680,
                   "fields": [
                     {"name": "Author", "value": "${{ github.event.pusher.name }}", "inline": true},
                     {"name": "Branch", "value": "${{ github.ref }}", "inline": true},
                     {"name": "Items to deploy", "value": "${{ env.FINAL_DEPLOY }}"},
                     {"name": "Updated Quiz(s)", "value": "${{ env.QUIZ }}"}
                   ]
                 }]
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
