name: Notify Discord of MDXCanvas Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MDXCanvas
        run: pip install mdxcanvas

      - name: Run MDXCanvas
        run: |
              export CANVAS_API_TOKEN=${{ secrets.DEPLOY_KEY }}
              echo "Avatar URL: ${{ github.actor }}@avatar" 

      - name: Send notification to Discord
        run: |
              export DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}
              python ${{ github.workspace }}/.github/scripts/send_discord_message.py --description "${{ github.event.head_commit.message }}" --message "${{ env.MESSAGE }} --author "${{ github.event.pusher.name }}" --author-icon "${{ github.actor }}@avatar" --branch "${{ github.ref }}""
