name: Notify Discord of MDXCanvas Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MDXCanvas
        run: pip install mdxcanvas

      - name: Run MDXCanvas
        run: | 
              export CANVAS_API_TOKEN=${{ secrets.DEPLOY_KEY }}
              echo "TO_DEPLOY"=$(mdxcanvas --course-info ${{ github.workspace }}/scratch/testing_course_info.json ${{ github.workspace }}/scratch/sample-content.canvas.md.xml --dryrun) >> $GITHUB_ENV

      - name: Clean up TO_DEPLOY variable
        run: |
          CLEANED_DEPLOY=$(echo "${{ env.TO_DEPLOY }}" | sed -e 's/Items to deploy: //g' -e 's/ - /\n/g')
          echo "TO_DEPLOY=${CLEANED_DEPLOY}" >> $GITHUB_ENV


      - name: Send commit info to Discord
        run: |
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub Actions",
                 "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                 "embeds": [{
                   "title": "Canvas Updates",
                   "description": "`${{ github.event.head_commit.message }}`",
                   "color": 16711680,
                   "fields": [
                     {"name": "Author", "value": "${{ github.event.pusher.name }}", "inline": true},
                     {"name": "Branch", "value": "${{ github.ref }}", "inline": true},
                     {"name": "Items to deploy", "value": "${{ env.TO_DEPLOY }}"},
                     {"name": "Updated Quiz(s)", "value": "${{ env.QUIZ }}"}
                   ]
                 }]
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
