name: Notify Discord of MDXCanvas Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MDXCanvas
        run: pip install mdxcanvas==0.3.18

      - name: Get User Avatar URL
        id: avatar
        run: |
          AVATAR_URL=$(curl -s https://api.github.com/users/${{ github.actor }} | jq -r '.avatar_url')
          echo "AVATAR_URL=$AVATAR_URL" >> $GITHUB_ENV

      - name: Run MDXCanvas
        id: run_mdxcanvas
        run: |
          export CANVAS_API_TOKEN=${{ secrets.DEPLOY_KEY }}
          mdxcanvas --course-info ${{ github.workspace }}/scratch/testing_course_info.json \
                    ${{ github.workspace }}/scratch/sample-content.canvas.md.xml 2>&1 | tee mdxcanvas_output.log

          echo "MDXCANVAS_RESULT<<EOF" >> $GITHUB_ENV
          cat mdxcanvas_output.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send notification to Discord
        run: |
          export TEST_CANVAS_DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK_URL }}
          python ${{ github.workspace }}/.github/scripts/send_discord_message.py \
            --message "$MDXCANVAS_RESULT" \
            --author "${{ github.actor }}" \
            --author-icon "$AVATAR_URL" \
            --branch "${{ github.ref }}"
