name: Notify Discord of MDXCanvas Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: | 
          # Run the program
          echo "Installing MDXCanvas"
          pip install mdxcanvas
          echo "Set env var"
          export CANVAS_API_TOKEN=${{ secrets.DEPLOY_KEY }}
          echo "Installed MDXCanvas"
          mdxcanvas --course-info ${{ github.workspace }}/scratch/testing_course_info.json ${{ github.workspace }}/scratch/sample-content.canvas.md.xml
          
          DEPLOYED_ASSIGNMENTS=$(grep "Deploying assignment" your_log_file.log | awk -F 'Deploying ' '{print $2}' | paste -sd '\n' -)
          DEPLOYED_QUIZZES=$(grep "Deploying quiz" your_log_file.log | awk -F 'Deploying ' '{print $2}' | paste -sd '\n' -)

          # Export for GitHub Actions
          echo "DEPLOYED=$DEPLOYED_ASSIGNMENTS" >> $GITHUB_ENV
          echo "QUIZ=$DEPLOYED_QUIZZES" >> $GITHUB_ENV

      - name: Send commit info to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub Actions",
                 "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                 "embeds": [{
                   "title": "Canvas Updates",
                   "description": "`${{ github.event.head_commit.message }}`",
                   "color": 16711680,
                   "fields": [
                     {"name": "Author", "value": "${{ github.event.pusher.name }}", "inline": true},
                     {"name": "Branch", "value": "${{ github.ref }}", "inline": true},
                     {"name": "Deployed Assignment(s)", "value": "${{ env.DEPLOYED }}"},
                     {"name": "Updated Quiz(s)", "value": "${{ env.QUIZ }}"}
                   ]
                 }]
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
          
          
