name: pypi_build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [merged]

jobs:
  check-mdxcanvas-version:
    uses: ./.github/workflows/check-mdxcanvas.yaml


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Poetry
        run: echo "hi"
